blog/urls.py
from django.urls import path, include
from django.contrib.auth.decorators import login_required


from . import views


app_name = 'blog'
urlpatterns = [
    path('', views.BlogListView.as_view(), name='index'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('post/<int:pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('blog/<slug:slug>/', login_required(views.BlogDetailView.as_view()), name='blog_detail'),
    path('blog/add/', views.BlogCreate.as_view(), name='blog_form'),
    path('re/<int:pk>/sub', views.SubView.as_view(), name='sub'),
    path('re/<int:pk>/unsub', views.UnSubView.as_view(), name='unsub'),
    path('ri/<int:pk>/read', views.ReadView.as_view(), name='read'),
    path('feed/', views.PostFeedView.as_view(), name='post_list'),
]

nekidaen/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('blog.urls', namespace='')),
    path('admin/', admin.site.urls),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.template.defaultfilters import slugify
from django.db.models.signals import post_save
from django.dispatch import receiver

from .utilities import email_subscriber


class Blog(models.Model):
    title = models.CharField(max_length=100, verbose_name='Название блога')
    description = models.TextField(verbose_name='Описание блога')
    author = models.OneToOneField(User, verbose_name='Пользователь', on_delete=models.CASCADE)
    sub = models.ManyToManyField(User, related_name='sub', blank=True, symmetrical=False,
                                 verbose_name='Подписчики блога')
    slug = models.SlugField(unique=True, verbose_name='Слаг')

    def __str__(self):
        return self.title

    def save(self):
        super(Blog, self).save()
        if not self.slug:
            self.slug = slugify(self.title)
            super(Blog, self).save()

    class Meta:
        verbose_name = 'Блог пользователя'
        verbose_name_plural = 'Блоги пользователей'


class Post(models.Model):
    title = models.CharField(max_length=200, verbose_name='Заголовок')
    content = models.TextField(verbose_name='Текст')
    created_at = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата публикации')
    blog = models.ForeignKey(Blog, verbose_name='Посты блога', on_delete=models.CASCADE)
    read = models.ManyToManyField(User, blank=True, verbose_name='Прочитано', related_name='read')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = 'Посты'
        verbose_name = 'Пост'
        ordering = ['-created_at']

@receiver(post_save, sender=Post)
def post_created(sender, instance, created, **kwargs):
    if created:
        blog_title = instance.title
        post_url = 'http://127.0.0.1:8000/posts/%s' % instance.pk
        user_emails = instance.blog.sub.values_list(
            'email', flat=True)
        for email in user_emails:
            email_subscriber(email, blog_title, post_url)

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import IntegrityError
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy
from django.views import generic

from .models import Blog, Post


class BlogCreate(LoginRequiredMixin, generic.CreateView):
    """"Создание блога, если блог есть, то HttpResponse"""
    model = Blog
    fields = ['title', 'description']
    template_name = 'blog_form.html'
    success_url = reverse_lazy('blog:index')

    def form_valid(self, form):
        try:
            form.instance.author = self.request.user
            return super().form_valid(form)
        except IntegrityError:
            return HttpResponse('У вас уже есть блог, больше нельзя')


class BlogListView(generic.ListView):
    """"Список блогов"""
    model = Blog
    context_object_name = 'blogs'
    template_name = 'index.html'
    paginate_by = 10


class BlogDetailView(generic.DetailView):
    """"Просмотр блога с постами """
    model = Blog
    context_object_name = 'blogs'
    slug_url_kwarg = 'slug'
    template_name = 'blog_detail.html'

    def get_context_data(self, **kwargs):
        context = super(BlogDetailView, self).get_context_data(**kwargs)
        context['posts'] = Post.objects.filter(blog__slug=self.kwargs['slug'])
        return context


class PostDetailView(generic.DetailView):
    """"Детальный просмотр постов"""
    model = Post
    context_object_name = 'post'
    template_name = 'post_detail.html'


class SubView(generic.CreateView):
    """"Подписка"""
    def post(self, request, *args, **kwargs):
        user = request.user
        blog = get_object_or_404(Blog, pk=kwargs.get('pk'))
        if not blog.sub.filter(pk=user.pk).exists():
            blog.sub.add(user)
        return render(request, 'help.html')


class UnSubView(generic.CreateView):
    """"Отписка"""
    def post(self, request, *args, **kwargs):
        user = request.user
        blog = get_object_or_404(Blog, pk=kwargs.get('pk'))
        if blog.sub.filter(pk=user.pk).exists():
            blog.sub.remove(user)
        return render(request, 'help.html')


class PostFeedView(generic.ListView):
    """"Моя лента"""
    model = Post
    context_object_name = 'posts'
    template_name = 'post_list.html'

    def get_queryset(self):
        return Post.objects.filter(blog__sub__in=[self.request.user])


class ReadView(generic.CreateView):
    """"Метка о прочтении"""
    def post(self, request, *args, **kwargs):
        user = request.user
        post = get_object_or_404(Post, pk=kwargs.get('pk'))
        if not post.read.filter(pk=user.pk).exists():
            post.read.add(user)
        return render(request, 'help.html')

blog/templates/base/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Главная страница{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-expand-sm bg-light navbar-light">
  <ul class="navbar-nav">
    <li class="nav-item active">
      <a class="nav-link" href="\">Главная страница</a>
    </li>
          {% if user.is_authenticated %}
    <li class="nav-item">
      <a class="nav-link" href="{% url 'blog:post_list' %}">Моя лента</a>
    </li>
      <li class="nav-item">
      <a class="nav-link" href="{% url 'blog:logout' %}">Выход</a>
      </li>
      {% else %}
    <li class="nav-item">
  <a class="nav-link" href="{% url 'blog:login' %}" role="button">Вход</a>
    </li>
            {% endif %}
  </ul>
</nav>
<div class="container">
      {% block content %}

      {% endblock %}
</div>

</body>
</html>

blog/templates/blog_detail.html
{%extends "base/base.html"%}
<title>{% block title %}{{blogs}}{% endblock %}</title>
{% block content %}
<div>
    {%  if request.user not in blogs.sub.all  %}
    <form action="{% url 'blog:sub' blogs.pk %}" method="post" class="form">
        {% csrf_token %}
        <button type="submit">Подписаться</button></form>
    {% else %}
    <form action="{% url 'blog:unsub' blogs.pk %}" method="post" class="form">
        {% csrf_token %}
        <button type="submit">Отписаться</button></form>
    {% endif %}
</div>
{% for post in posts %}
<div style="border:3px #00B344  solid;">
    <h1><a href="{% url 'blog:post_detail' post.pk %}">{{ post.title }}</a></h1>
    <p class="text-right ">Запись создана {{ post.created_at }}</p>
</div>
{% endfor %}
{% endblock %}

blog/templates/blog_form.html
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>

blog/templates/create_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

blog/templates/help.html
<nav class="navbar navbar-expand-sm bg-light navbar-light">
  <ul class="navbar-nav">
    <li class="nav-item active">
      <a class="nav-link" href="\">Блоги пользователй</a>
    </li>
          {% if user.is_authenticated %}
    <li class="nav-item">
      <a class="nav-link" href="{% url 'blog:post_list' %}">Мой лента</a>
    </li>
      <li class="nav-item">
      <a class="nav-link" href="{% url 'blog:logout' %}">Выход</a>
      </li>
      {% else %}
    <li class="nav-item">
  <a class="nav-link" href="{% url 'blog:login' %}" role="button">Вход</a>
    </li>
            {% endif %}
  </ul>
</nav>

blog/templates/index.html
{%extends "base/base.html"%}

{% block content %}
<h3>Блоги пользователей</h3>
{% for blog in blogs %}
    <div>
        <h1><a href="{% url 'blog:blog_detail' blog.slug %}">{{ blog.title }}</a></h1>
        <p>{{ blog.description }}</p>
        <p class="text-right ">Автор блога: {{ blog.author }}</p>
    </div>
{% endfor %}
{% endblock %}

blog/templates/post_detail.html
{%extends "base/base.html"%}
<title>{% block title %}{{post.title}}{% endblock %}</title>
{% block content %}
<div style="border:3px #00B344  solid;">
    <h1>{{ post.title }}</h1>
    <p>{{ post.content }}</p>
    <p class="text-right ">Запись создана {{ post.created_at }}</p>
</div>
{% endblock %}

blog/templates/post_list.html
{%extends "base/base.html"%}
<title>{% block title %}Моя лента{% endblock %}</title>
{% block content %}
<h2>Лента новостей</h2>
{% for post in posts %}
<div style="border:3px #00B344  solid;">
    {% if request.user not in post.read.all %}
    <form action="{% url 'blog:read' post.pk %}" method="post" class="form">
        {% csrf_token %}
    <button type="submit">отметить прочитанным</button></form>
    {% else %}
    <p>Пост прочитан</p>
    {% endif %}
    <h3><a href="{% url 'blog:blog_detail' post.blog.slug %}">{{ post.blog }}</a></h3>
    <h1>Заголовок: {{ post.title }}</h1>
    <p>{{ post.content }}</p>
    <p class="text-right ">Запись создана {{ post.created_at }}</p>
</div>
{% endfor %}
{% endblock %}